### ISSUE TITLE
Missing file  insertionSort.js

### ISSUE THREAD

**Issue by AdityaPai2398** [connor11528/coding-interviews#2]
https://github.com/connor11528/coding-interviews/blob/master/practice/algorithms/insertionSort.js

**Comment by connor11528** [comment]
Oh that's because it's way less efficient so don't worry about ever having to implement it. I'll delete the file at some point or you're welcome to submit a PR

> Insertion sort is a simple sorting algorithm that builds the final sorted array (or list) one item at a time. It is much less efficient on large lists than more advanced algorithms such as quicksort, heapsort, or merge sort.
